### ISSUE TITLE
Ruby 2.7 didn't have JSON.load_file method

### ISSUE THREAD

**Issue by elct9620** [ankane/tokenizers-ruby#26]
I got this error when using Ruby 2.7.7

```
undefined method `load_file' for JSON:Module (NoMethodError)
```

I think the reason is `.load_file` method is added after Ruby 3.0
https://ruby-doc.org/stdlib-2.7.0/libdoc/json/rdoc/JSON.html

**Comment by ankane** [comment]
Hey @elct9620, thanks for reporting! Will push a new release shortly.
