### ISSUE TITLE
Issues when deploying to Ubuntu 20.04

### ISSUE THREAD

**Issue by TheBrockEllis** [ankane/tokenizers-ruby#30]
I recently installed the tokenizers gem while working with the OpenAI API. When developing locally, everything was running very smoothly. This morning, I went to deploy the rails application to our staging environment and ran into a problem. The deployment (via capastrano) failed with this error message:

```01 LoadError: cannot load such file -- /var/www/personal-project/shared/bundle/ruby/2.7.0/gems/tokenizers-0.3.2-x86_64-linux-musl/lib/tokenizers/tokenizers```

I fulled removed the Tokenizer gem and was able to successfully deploy. I was also able to pin the dependency in the Gemfile to 0.3.1 and it deployed correctly.

I've attached the entire stack trace to this issue. 

I'm running a 2021 M1 Macbook. The target server is running Ubuntu 20.04.6 LTS hosted on Digital Ocean. Node version on both local and server is v16.20.0.

Please let me know what other information I can provide to be helpful!

[tokenizer-capistrano-failed-deployment.txt](https://github.com/ankane/tokenizers-ruby/files/11276455/tokenizer-capistrano-failed-deployment.txt)

**Comment by ankane** [comment]
Hi @TheBrockEllis, it looks like it's installed the musl version (`x86_64-linux-musl`) of the gem instead of the glibc version (`x86_64-linux`). What's the output of `bundle platform` on the server?

**Comment by TheBrockEllis** [comment]
`bundle platform` on the server:

```
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* ruby

Your Gemfile specifies a Ruby version requirement:
* ruby 2.7.2p137

Your current platform satisfies the Ruby version requirement.
```

And locally, incase it helps:

```
Your platform is: arm64-darwin21

Your app has gems that work on these platforms:
* ruby

Your Gemfile specifies a Ruby version requirement:
* ruby 2.7.2p137

Your current platform satisfies the Ruby version requirement.
```

**Comment by ankane** [comment]
Thanks, can you also paste any `tokenizers` lines from `Gemfile.lock`?

Also, try running the following to see if it fixes it:

```sh
bundle lock --add-platform x86_64-linux
```

**Comment by TheBrockEllis** [comment]
Ran `bundle lock --add-platform x86_64-linux` locally and it updated a few lines in the `Gemfile.lock`

```
       racc (~> 1.4)
+    nokogiri (1.12.5-x86_64-linux)
+      racc (~> 1.4)
     oj (3.13.21)
     orm_adapter (0.5.0)
     pg (1.2.3)
@@ -364,6 +366,7 @@ GEM
     thor (1.1.0)
     tokenizers (0.3.1)
       rb_sys
+    tokenizers (0.3.3-x86_64-linux)
```

Attempted to deploy and got the same error: 

Rubygems was at 3.1.4 on both the server and locally. Updated to 3.4.12 on the server and ran into the same issues as before. `Caused by:
LoadError: /lib/x86_64-linux-gnu/libc.so: invalid ELF header - /var/www/fanword-boost/shared/bundle/ruby/2.7.0/gems/tokenizers-0.3.3-x86_64-linux-musl/lib/tokenizers/2.7/tokenizers.so`

Check:
```
root@staging:~# gem -v
3.1.4
```

Updated it:

```
root@staging:~# gem update --system
Updating rubygems-update
Fetching rubygems-update-3.4.12.gem
Successfully installed rubygems-update-3.4.12
Parsing documentation for rubygems-update-3.4.12
Installing ri documentation for rubygems-update-3.4.12
...
```

Result: 
```
root@staging:~# gem -v
3.4.12
```

No change. Still have the same error as before. At the moment, pinning the gem to 0.3.1 seems to unblock us from deploying, so no need to treat this as urgent or anything. Would love to be able to help anyone else out that runs into a similar error down the road.

**Comment by ankane** [comment]
You'll probably need to uninstall any previous versions with `gem uninstall tokenizers --all` after running `gem update --system`.

For future readers, this affects Ruby 2.7 and 3.0, which have RubyGems < 3.3 installed by default.
