### ISSUE TITLE
Add optional punctuation cleanup during decoding - clean_up_tokenization equivalent

### ISSUE THREAD

**Issue by w-zygmuntowicz** [ankane/tokenizers-ruby#33]
Hi there!

I'm really glad you have made this gem available It's just the best. It's just I have that small issue – when you try to decode previously encoded string containing punctuation marks there are extra spaces added before them.

Eg.
```ruby
tokenizer = Tokenizers.from_pretrained(TOKENIZER_ID)
encoding = tokenizer.encode("Who are you?")
tokenizer.decode(encoding.ids) # => "Who are you ?"
```

I have made a small research on how it's made in the python implementation and there is a method called [clean_up_tokenization](https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L3873C9-L3873C30) it's being called in the last if statement of the [_decode](https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_fast.py#L614) method.

So I have a few questions:
  1. Would you consider adding a similar feature to this gem for optional punctuation cleanup?
  2. If so, would it be better to implement this cleanup logic in Ruby or Rust?

I'm happy to contribute to a solution if this change aligns with your project goals. I'm comfortable working in either Ruby or Rust. Please let me know how you'd like to proceed!

**Comment by ankane** [comment]
Hi @w-zygmuntowicz, which tokenizer are you using (if it's a public one)? It looks like Tokenizers has this functionality [built-in](https://github.com/huggingface/tokenizers/blob/29fef1e7aa47216d3b9fe4a9416f6021c14b4561/tokenizers/src/decoders/wordpiece.rs#L31).

**Comment by w-zygmuntowicz** [comment]
Ahh I see, it seems I'm using a BPE Decoder.  It's a public model based on Herbert for the Polish language.

So, correct me if I'm wrong, this issue should probably be in the other repository?

**Comment by ankane** [comment]
I'd first check if the Python output matches the Ruby output.

```python
from tokenizers import Tokenizer

tokenizer = Tokenizer.from_pretrained('ipipan/silver-retriever-base-v1')
encoding = tokenizer.encode('...')
print(tokenizer.decode(encoding.ids))
```

If so, it might be better addressed upstream.

**Comment by w-zygmuntowicz** [comment]
I have checked that and the outputs don't match:

| input | ruby | python |
|---|---|---|
| `How are you?` | `How are you ?` | `How are you?` |

**Comment by w-zygmuntowicz** [comment]
Done! :)
