### ISSUE TITLE
Using gem on Alpine and ARM-based CPUs

### ISSUE THREAD

**Issue by robinroestenburg** [ankane/tokenizers-ruby#36]
Related to #27.

We are running our Alpine containers on AWS Graviton instances, that are using 64-bit ARM-based CPUs. Would it be possible for you to also create a MUSL compatible version of the gem for that (I believe that would be an aarch64-linux-musl build)?

**Comment by ankane** [comment]
Just pushed 0.5.1, which includes support.

**Comment by robinroestenburg** [comment]
Thanks @ankane!
