### ISSUE TITLE
Support to Ruby 3.2.0 (release 0.2.1)

### ISSUE THREAD

**Issue by vickymadrid03** [ankane/tokenizers-ruby#5]
Hi! First of all, thanks for making and maintaining this gem! 🙌 

I was wondering when you expect to release the last version of the gem with support to Ruby 3.2.0. We're using it in a project and it seems to be the only missing piece for us to upgrade it.

Thanks in advance!

PS: Asking this because I noticed the commit with the changes was already merged https://github.com/ankane/tokenizers-ruby/commit/1f89484e7552b28b3e4dd9e5fccaf57d26d169f1

**Comment by ankane** [comment]
Hey @vickymadrid03, hopefully soon. I'm waiting to ship a precompiled version, which currently relies on two other projects, but you can point your Gemfile to GitHub to build from source in the meantime (requires a Rust compiler).

**Comment by ankane** [comment]
0.2.1 is out 🎉

**Comment by vickymadrid03** [comment]
Thank you @ankane! 🎉
