### ISSUE TITLE
Version 0.2 relying on an old version of libssl

### ISSUE THREAD

**Issue by kwi** [ankane/tokenizers-ruby#6]
Hey @ankane !

Thank you for making this gem, it's great for Rubyists like us to still be able to play easily with the new AI trend ;)
I love that you embedded the libs in the 0.2 version of the gem as compilation was really taking forever and required way too much libs, however it seems that it now relies on an outdated version of libssl and I haven't figured out to get it running on Ubuntu in a prod environment. libssl.so.10

Do you think it's possible to upgrade it easily?

Thanks!

```
Caused by:
LoadError: libssl.so.10: cannot open shared object file: No such file or directory - /shared/bundle/ruby/3.1.0/gems/tokenizers-0.2.1-x86_64-linux/lib/tokenizers/3.1/tokenizers.so
/shared/bundle/ruby/3.1.0/gems/tokenizers-0.2.1-x86_64-linux/lib/tokenizers.rb:3:in `require'
/shared/bundle/ruby/3.1.0/gems/tokenizers-0.2.1-x86_64-linux/lib/tokenizers.rb:3:in `<top (required)>'
/releases/20230113084850/config/application.rb:19:in `<top (required)>'
/releases/20230113084850/Rakefile:4:in `require_relative'
/releases/20230113084850/Rakefile:4:in `<top (required)>'
/shared/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/deploy/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
/home/deploy/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
rails aborted!
```

**Comment by ankane** [comment]
Hey @kwi, thanks for reporting! Was able to reproduce. Will figure out some fix (either upgrading OpenSSL or switching to Rustls).

**Comment by kwi** [comment]
Wow, thank you @ankane for being so reactive!
Awesome, looking forward to a new release soon then :)

**Comment by ankane** [comment]
Just pushed a new version (0.2.2). After trying a number of options, ended up moving the download logic to Ruby, which reduced the extension size by half and removed the need to link or vendor a separate TLS library.

Thanks again for reporting!

**Comment by kwi** [comment]
Boom! Love it @ankane - Will try to that new version right away.
Thank you for being so prompt solving this! Will make my deployments so much easier!
