### ISSUE TITLE
More flexible handling of special tokens

### ISSUE THREAD

**Issue by petergoldstein** [ankane/tokenizers-ruby#8]
I may be missing something, but it looks like it's not currently possible to encode with special tokens because the special tokens argument is hardcoded to false in the encode method.  Ideally I'd like to be able to encode (and decode) with special tokens.

I think the big challenge here is the lack of support for default arguments in Rust (and the corresponding Ruby/Rust interface).  Ideally we'd like the special tokens value to have a default for encode, and be able to override that default value.

One option (which might free up other opportunities) is to add a wrapper class - the Rust Tokenizer interface would be implemented on an internal class, while the external class returned from factory methods would be a Ruby wrapper class.  That Ruby wrapper could handle things like default arguments.  This appears to be (essentially) how the Python library works.  It could also make it easier to implement batch encoding, sequences, and other related features.

I'm not sure if there's an appetite for this sort of change, or if there's another solution that @ankane may have in mind.  Thoughts?

**Comment by ankane** [comment]
Hey @petergoldstein, definitely want to support more of the Tokenizers API. Can you share the Python version of what you're trying to do?

```python
from tokenizers import ...

# ...
```

**Comment by petergoldstein** [comment]
Sure.

Here's an example of an encode which skips special tokens:

```
from tokenizers import Tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
sample = 'where is Himalayas in the world map?'
encoding = tokenizer.encode(sample, add_special_tokens=False)
print(encoding)
print(tokenizer.convert_ids_to_tokens(encoding))
```

which results in

```
[1187, 1110, 15619, 27399, 1116, 1107, 1103, 1362, 4520, 136]
['where', 'is', 'Him', '##alaya', '##s', 'in', 'the', 'world', 'map', '?']
```
This is what `tokenizers-ruby` does, because of the `false` on this line - https://github.com/ankane/tokenizers-ruby/blob/35295db6a3d23a54d40f2145b792d253f3567fd8/ext/tokenizers/src/tokenizer.rs#L42

But we can instead pass `add_special_tokens=True` (or just don't pass anything, as this is the default in the Python library) like so:

```
from tokenizers import Tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
sample = 'where is Himalayas in the world map?'
encoding = tokenizer.encode(sample, add_special_tokens=True)
print(encoding)
print(tokenizer.convert_ids_to_tokens(encoding))
```
and we get

```
[101, 1187, 1110, 15619, 27399, 1116, 1107, 1103, 1362, 4520, 136, 102]
['[CLS]', 'where', 'is', 'Him', '##alaya', '##s', 'in', 'the', 'world', 'map', '?', '[SEP]']
```

which now includes the [CLS] and [SEP] separators.

I'd like to be able to do the latter (get the special tokens), but ideally like the Python case I'd like to be able to control what I get at encode time.

**Comment by petergoldstein** [comment]
Ideally we'd be able to add most, if not all, of the capabilities of "fast tokenizers" (that is tokenizers written in Rust) as described here - https://huggingface.co/course/chapter6/3 (i.e. type_ids, offsets, sequences, "batch encoding", etc.). But that's a bigger chunk of work.

**Comment by ankane** [comment]
Ideally, the code would match the Python library as closely as possible (this isn't the case at all currently).

Since Magnus currently doesn't support keyword arguments (like PyO3), let's go with [this pattern](https://github.com/ankane/tokenizers-ruby/commit/c479394dc2663fbf5b3c05c067b11241878a5db4) for methods that use them.

Also, it looks like the default value for `add_special_tokens` should be true. Will make that change in 0.3.0.

**Comment by petergoldstein** [comment]
Ah.  Didn't realize you could open up the Ruby class like that, although I should have.  That's basically what I had in mind for a `wrapper class`.  Looks good.  

I'm happy to help out adding functions if that's useful. Just let me know.

One question - there are a number of other methods like `token_to_chars` which are implemented in Rust, but are easy to implement in Ruby if you wanted to keep the interface to Rust narrow.  If we wanted to add those functions to the interface would you prefer calling the native Rust, or would you rather implement in Ruby based on the collection methods already exported?

**Comment by ankane** [comment]
Yeah, feel free to add things. For methods like `token_to_chars`, let's go with Rust if that's how the Python library does it.
